### ISSUE TITLE
Apply a for-comprehension

### ISSUE THREAD

**Issue by koljamaier** [adamgfraser/0-to-100-with-zio-test#1]
Hello Adam,

thanks for the great example! I stumbled upon it by watching the corresponding YT video https://www.youtube.com/watch?v=qDFfVinjDPQ&t 
While it was a nice talk I found it hard to understand the method `topContributors`*. I was actually expecting an artificial error that we would later discover when implementing tests - turned out I was wrong and the method just works fine. So I tried to make it more "readable" to myself by using for-comprehensions: 

```
    for {
      repos <- Github.getRepos(language, limit)
      contributorsM <- ZIO.foreachPar(repos)(Github.getContributors)
      contributor <- contributorsM.flatten
      notScalaStewaredContributor <- notScalaSteward(contributor)
    } yield contributionsByUser(notScalaStewaredContributor)
```
Sadly this and some other variants that I tried out does not compile.
So my question would be: Is it possible to create a for-comprehension for this method? And if yes why did you not use the for-Comprehension? Concretly the `.map(_flatten)` part **after** a `.flatMap` operation was really hard to understand for me when reading the first time (opening the IDE made it alot easier)

Cheers 

\* Impl of `topContributors`:
```
  def topContributors(
      language: String,
      limit: Int
  ): ZIO[Github, Throwable, List[Contributor]] =
    Github
      .getRepos(language, limit)
      .flatMap(ZIO.foreachPar(_)(Github.getContributors))
      .map(_.flatten)
      .map(notScalaSteward)
      .map(contributionsByUser)
```

**Comment by koljamaier** [comment]
@adamgfraser maybe I am confusing it but could I also use a `.collect` in combination with this `foreach`? I was inspired by this example https://github.com/zio/zio/issues/3942

**Comment by koljamaier** [comment]
@adamgfraser I now found a way how to do it (with the cool desugar functionality from IntelliJ I could work my way through a bit clearer):

```
    val test = for {
      repos <- Github.getRepos(language, limit)
      contributorsM <- ZIO.foreachPar(repos)(Github.getContributors)
      // contributor <- contributorsM.flatten
      // notScalaStewaredContributor <- notScalaSteward(contributor)
      // contrubutionsByUser(...)
    } yield (contributorsM.flatten)

    test.map(notScalaSteward).map(contributionsByUser)
```

But what I would actually prefer doing would be to use the `.map` statements inside of the `for`comprehension. i know that a for-comprehension basically is the combination of `flatMap...flatMap...map` - so is this even possible?

**Comment by adamgfraser** [comment]
@koljamaier You can use pure functions within a for comprehension using the `=` operator instead of the `<-` operator. For example, you can rewrite the implementation of `topContributors` using a for comprehension like this:

```scala
def topContributors(
    language: String,
    limit: Int
): ZIO[Github, Throwable, List[Contributor]] =
for {
  repos        <- Github.getRepos(language, limit)
  contributors <- ZIO.foreachPar(repos)(Github.getContributors)
  flattened     = contributors.flatten
  filtered      = notScalaSteward(flattened)
  grouped       = contributionsByUser(filtered)
} yield grouped
```

I think the tricky thing here is the `ZIO.foreachPar` call returns a `List[List[Contributor]]` because `getContributors` itself returns a `List[Contributor]`. So when we call `flatten` we aren't calling it on `ZIO` but on `List`.

I used the chained operators because I thought it nicely reflected the idea of this as a "data pipeline" where we are getting some data and repeatedly applying transformations to it but as you can see you can use a for comprehension as well.

**Comment by koljamaier** [comment]
Thank you very much for this detailed explanation! Using `=` is very powerful. I somehow did not know about it
